version: "3.7"

services:

  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: ./Docker/nginx/Dockerfile
    restart: always
    ports:
      - ${HTTP_PORT}:80
    depends_on:
      - php
    networks:
      - saedocker

  php:
    container_name: php
    build:
      context: ../
      dockerfile: ./Docker/php/Dockerfile
    environment:
      APP_ENV: ${ENV}
      APP_DEBUG: ${APP_DEBUG}
    command: /entrypoint.sh
    restart: always
    networks:
      - saedocker

networks:
  saedocker:
    driver: bridge
